#include "manipulator.h"
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif
#define EPS 1e-9
#define MEPS 1e-12

static double clamp(double v,double lo,double hi){return v<lo?lo:(v>hi?hi:v);} 
static double limit_abs(double v,double m){return clamp(v,-m,m);} 
static double norm_angle(double a){while(a>M_PI)a-=2*M_PI;while(a<-M_PI)a+=2*M_PI;return a;}
static double angle_dist(double a,double b){return fabs(norm_angle(a-b));}

static int inv3(const double A[3][3], double B[3][3]){
 double a=A[0][0],b=A[0][1],c=A[0][2],d=A[1][0],e=A[1][1],f=A[1][2],g=A[2][0],h=A[2][1],i=A[2][2];
 double det=a*(e*i-f*h)-b*(d*i-f*g)+c*(d*h-e*g); if(fabs(det)<MEPS)return 0;
 B[0][0]=(e*i-f*h)/det; B[0][1]=-(b*i-c*h)/det; B[0][2]=(b*f-c*e)/det;
 B[1][0]=-(d*i-f*g)/det; B[1][1]=(a*i-c*g)/det; B[1][2]=-(a*f-c*d)/det;
 B[2][0]=(d*h-e*g)/det; B[2][1]=-(a*h-b*g)/det; B[2][2]=(a*e-b*d)/det; return 1;
}

void manipulator_default_config(ManipulatorConfig *c){
 if(!c) return;
 memset(c,0,sizeof(*c)); c->d1=MANIP_DEFAULT_D1;c->a2=MANIP_DEFAULT_A2;c->q1_maximum_velocity=MANIP_DEFAULT_Q1_MAX_VELOCITY;c->q4_minimum_position=MANIP_DEFAULT_Q4_MIN_POSITION;c->q4_maximum_position=MANIP_DEFAULT_Q4_MAX_POSITION;c->q4_maximum_velocity=MANIP_DEFAULT_Q4_MAX_VELOCITY;c->damping=MANIP_DEFAULT_DAMPING;
 c->q2_actuator=(ManipulatorLinearActuatorGeometry){MANIP_DEFAULT_Q2_LINK_FIXED_1,MANIP_DEFAULT_Q2_LINK_FIXED_2,MANIP_DEFAULT_Q2_LINK_ANGLE_OFFSET,MANIP_DEFAULT_Q2_LINK_DIRECTION,MANIP_DEFAULT_Q2_ACTUATOR_MIN_LENGTH,MANIP_DEFAULT_Q2_ACTUATOR_MAX_LENGTH,MANIP_DEFAULT_Q2_LINEAR_MAX_VELOCITY};
 c->q3_actuator=(ManipulatorLinearActuatorGeometry){MANIP_DEFAULT_Q3_LINK_FIXED_1,MANIP_DEFAULT_Q3_LINK_FIXED_2,MANIP_DEFAULT_Q3_LINK_ANGLE_OFFSET,MANIP_DEFAULT_Q3_LINK_DIRECTION,MANIP_DEFAULT_Q3_ACTUATOR_MIN_LENGTH,MANIP_DEFAULT_Q3_ACTUATOR_MAX_LENGTH,MANIP_DEFAULT_Q3_LINEAR_MAX_VELOCITY};
}
ManipulatorStatus manipulator_validate_config(const ManipulatorConfig *c){
 if(!c) return MANIP_ERROR_INVALID_ARGUMENT;
 if(fabs(c->a2)<EPS||c->q1_maximum_velocity<0||c->q4_maximum_velocity<0||c->q4_minimum_position>c->q4_maximum_position||c->damping<0)return MANIP_ERROR_INVALID_GEOMETRY;
 const ManipulatorLinearActuatorGeometry *g[2]={&c->q2_actuator,&c->q3_actuator}; for(int k=0;k<2;k++)if(fabs(g[k]->fixed_length_1)<EPS||fabs(g[k]->fixed_length_2)<EPS||fabs(g[k]->direction)<EPS||g[k]->minimum_length>g[k]->maximum_length||g[k]->maximum_velocity<0)return MANIP_ERROR_INVALID_GEOMETRY; return MANIP_OK;
}
const char *manipulator_status_string(ManipulatorStatus s){switch(s){case MANIP_OK:return "OK";case MANIP_ERROR_INVALID_ARGUMENT:return "invalid argument";case MANIP_ERROR_INVALID_GEOMETRY:return "invalid geometry";case MANIP_ERROR_OUTSIDE_LIMITS:return "outside physical limits";case MANIP_ERROR_UNREACHABLE:return "unreachable position";case MANIP_ERROR_SINGULAR:return "singular configuration";case MANIP_ERROR_NUMERICAL:return "numerical error";default:return "unknown error";}}

ManipulatorStatus manipulator_joint_angle_to_linear_length(double q,const ManipulatorLinearActuatorGeometry *g,double *l){if(!g||!l)return MANIP_ERROR_INVALID_ARGUMENT;double p=g->direction*q+g->angle_offset;double s=g->fixed_length_1*g->fixed_length_1+g->fixed_length_2*g->fixed_length_2-2*g->fixed_length_1*g->fixed_length_2*cos(p);if(s<-EPS)return MANIP_ERROR_NUMERICAL;if(s<0)s=0;*l=sqrt(s);return(*l<g->minimum_length-EPS||*l>g->maximum_length+EPS)?MANIP_ERROR_OUTSIDE_LIMITS:MANIP_OK;}
ManipulatorStatus manipulator_linear_length_to_joint_angle(double l,const ManipulatorLinearActuatorGeometry *g,double *q){if(!g||!q)return MANIP_ERROR_INVALID_ARGUMENT;if(l<g->minimum_length-EPS||l>g->maximum_length+EPS)return MANIP_ERROR_OUTSIDE_LIMITS;double c=(g->fixed_length_1*g->fixed_length_1+g->fixed_length_2*g->fixed_length_2-l*l)/(2*g->fixed_length_1*g->fixed_length_2);if(c>1&&c<1+EPS)c=1;if(c<-1&&c>-1-EPS)c=-1;if(c<-1||c>1)return MANIP_ERROR_INVALID_GEOMETRY;*q=(acos(c)-g->angle_offset)/g->direction;return MANIP_OK;}
ManipulatorStatus manipulator_joint_velocity_to_linear_velocity(double q,double qd,const ManipulatorLinearActuatorGeometry *g,double *ld){double l;ManipulatorStatus s=manipulator_joint_angle_to_linear_length(q,g,&l);if(s!=MANIP_OK)return s;if(fabs(l)<EPS)return MANIP_ERROR_SINGULAR;double p=g->direction*q+g->angle_offset;*ld=g->fixed_length_1*g->fixed_length_2*sin(p)*g->direction*qd/l;return MANIP_OK;}
ManipulatorStatus manipulator_linear_velocity_to_joint_velocity(double q,double ld,const ManipulatorLinearActuatorGeometry *g,double *qd){double l;ManipulatorStatus s=manipulator_joint_angle_to_linear_length(q,g,&l);if(s!=MANIP_OK)return s;double p=g->direction*q+g->angle_offset, den=g->direction*g->fixed_length_1*g->fixed_length_2*sin(p);if(fabs(den)<EPS)return MANIP_ERROR_SINGULAR;*qd=l*ld/den;return MANIP_OK;}

void manipulator_compute_forward_matrix(const ManipulatorConfig *c,double q1,double q2,double q3,double q4,double T[4][4]){double c1=cos(q1),s1=sin(q1),c2=cos(q2),s2=sin(q2),q23=q2+q3,c23=cos(q23),s23=sin(q23),r=c->a2*c2+q4*s23;double M[4][4]={{c1*c23,-s1,c1*s23,c1*r},{s1*c23,c1,s1*s23,s1*r},{-s23,0,c23,c->d1-c->a2*s2+q4*c23},{0,0,0,1}};memcpy(T,M,sizeof(M));}
void manipulator_compute_geometric_jacobian(const ManipulatorConfig *c,double q1,double q2,double q3,double q4,double J[6][4]){double c1=cos(q1),s1=sin(q1),c2=cos(q2),s2=sin(q2),q23=q2+q3,c23=cos(q23),s23=sin(q23),r=c->a2*c2+q4*s23,k=-c->a2*s2+q4*c23;double M[6][4]={{-s1*r,c1*k,c1*q4*c23,c1*s23},{c1*r,s1*k,s1*q4*c23,s1*s23},{0,-r,-q4*s23,c23},{0,-s1,-s1,0},{0,c1,c1,0},{1,0,0,0}};memcpy(J,M,sizeof(M));}
void manipulator_extract_translational_jacobian(const double J[6][4],double V[3][4]){for(int r=0;r<3;r++)for(int k=0;k<4;k++)V[r][k]=J[r][k];}
ManipulatorStatus manipulator_update_state_from_joints(const ManipulatorConfig *c,double q1,double q2,double q3,double q4,ManipulatorState *s){if(!c||!s)return MANIP_ERROR_INVALID_ARGUMENT;if(q4<c->q4_minimum_position-EPS||q4>c->q4_maximum_position+EPS)return MANIP_ERROR_OUTSIDE_LIMITS;ManipulatorStatus e=manipulator_joint_angle_to_linear_length(q2,&c->q2_actuator,&s->q2_actuator_length);if(e!=MANIP_OK)return e;e=manipulator_joint_angle_to_linear_length(q3,&c->q3_actuator,&s->q3_actuator_length);if(e!=MANIP_OK)return e;s->q1=q1;s->q2=q2;s->q3=q3;s->q4=q4;manipulator_compute_forward_matrix(c,q1,q2,q3,q4,s->T04);s->x=s->T04[0][3];s->y=s->T04[1][3];s->z=s->T04[2][3];manipulator_compute_geometric_jacobian(c,q1,q2,q3,q4,s->J);manipulator_extract_translational_jacobian(s->J,s->Jv);return MANIP_OK;}
ManipulatorStatus manipulator_update_state_from_actuators(const ManipulatorConfig *c,double q1,double l2,double l3,double q4,ManipulatorState *s){double q2,q3;ManipulatorStatus e=manipulator_linear_length_to_joint_angle(l2,&c->q2_actuator,&q2);if(e!=MANIP_OK)return e;e=manipulator_linear_length_to_joint_angle(l3,&c->q3_actuator,&q3);if(e!=MANIP_OK)return e;return manipulator_update_state_from_joints(c,q1,q2,q3,q4,s);}

static void add_sol(ManipulatorIKSolution sol[],size_t *n,double q1,double q2,double q3,double q4){q1=norm_angle(q1);q2=norm_angle(q2);q3=norm_angle(q3);for(size_t i=0;i<*n;i++)if(angle_dist(sol[i].q1,q1)<EPS&&angle_dist(sol[i].q2,q2)<EPS&&angle_dist(sol[i].q3,q3)<EPS)return;if(*n<MANIP_MAX_IK_SOLUTIONS)sol[(*n)++]=(ManipulatorIKSolution){q1,q2,q3,q4};}
static void solve23(const ManipulatorConfig *c,double q1,double r,double h,double q4,ManipulatorIKSolution sol[],size_t *n){double s=(r*r+h*h-c->a2*c->a2-q4*q4)/(2*c->a2*q4);if(s>1&&s<1+EPS)s=1;if(s<-1&&s>-1-EPS)s=-1;if(s<-1||s>1)return;double a=asin(s), cand[2]={a,M_PI-a};for(int k=0;k<2;k++){double q3=norm_angle(cand[k]),A=c->a2+q4*sin(q3),B=q4*cos(q3),q2=atan2(B*r-A*h,A*r+B*h),l;if(manipulator_joint_angle_to_linear_length(q2,&c->q2_actuator,&l)!=MANIP_OK)continue;if(manipulator_joint_angle_to_linear_length(q3,&c->q3_actuator,&l)!=MANIP_OK)continue;add_sol(sol,n,q1,q2,q3,q4);}}
ManipulatorStatus manipulator_inverse_position_for_q4(const ManipulatorConfig *c,double x,double y,double z,double q4,ManipulatorIKSolution sol[],size_t *n){if(!c||!sol||!n)return MANIP_ERROR_INVALID_ARGUMENT;*n=0;if(q4<c->q4_minimum_position-EPS||q4>c->q4_maximum_position+EPS)return MANIP_ERROR_OUTSIDE_LIMITS;double r=hypot(x,y),h=z-c->d1;if(r<EPS){solve23(c,0,0,h,q4,sol,n);return*n?MANIP_ERROR_SINGULAR:MANIP_ERROR_UNREACHABLE;}double q=atan2(y,x);solve23(c,q,r,h,q4,sol,n);solve23(c,norm_angle(q+M_PI),-r,h,q4,sol,n);return*n?MANIP_OK:MANIP_ERROR_UNREACHABLE;}

ManipulatorStatus manipulator_estimate_joint_velocity(const ManipulatorConfig *c,const ManipulatorState *s,ManipulatorCartesianVelocity v,ManipulatorJointVelocity *qd){if(!c||!s||!qd)return MANIP_ERROR_INVALID_ARGUMENT;double A[3][3]={{0}},B[3][3],aux[3]={0},vv[3]={v.vx,v.vy,v.vz},q[4]={0};for(int r=0;r<3;r++)for(int k=0;k<3;k++){for(int j=0;j<4;j++)A[r][k]+=s->Jv[r][j]*s->Jv[k][j];if(r==k)A[r][k]+=c->damping*c->damping;}if(!inv3(A,B))return MANIP_ERROR_NUMERICAL;for(int r=0;r<3;r++)for(int k=0;k<3;k++)aux[r]+=B[r][k]*vv[k];for(int j=0;j<4;j++)for(int r=0;r<3;r++)q[j]+=s->Jv[r][j]*aux[r];*qd=(ManipulatorJointVelocity){q[0],q[1],q[2],q[3]};return MANIP_OK;}
ManipulatorStatus manipulator_joint_velocity_to_actuator_command(const ManipulatorConfig *c,const ManipulatorState *s,ManipulatorJointVelocity req,ManipulatorActuatorCommand *cmd,ManipulatorJointVelocity *sat){if(!c||!s||!cmd||!sat)return MANIP_ERROR_INVALID_ARGUMENT;cmd->q1_rotary_velocity=limit_abs(req.q1_dot,c->q1_maximum_velocity);ManipulatorStatus e=manipulator_joint_velocity_to_linear_velocity(s->q2,req.q2_dot,&c->q2_actuator,&cmd->q2_linear_velocity);if(e!=MANIP_OK)return e;e=manipulator_joint_velocity_to_linear_velocity(s->q3,req.q3_dot,&c->q3_actuator,&cmd->q3_linear_velocity);if(e!=MANIP_OK)return e;cmd->q2_linear_velocity=limit_abs(cmd->q2_linear_velocity,c->q2_actuator.maximum_velocity);cmd->q3_linear_velocity=limit_abs(cmd->q3_linear_velocity,c->q3_actuator.maximum_velocity);cmd->q4_linear_velocity=limit_abs(req.q4_dot,c->q4_maximum_velocity);if((s->q4<=c->q4_minimum_position+EPS&&cmd->q4_linear_velocity<0)||(s->q4>=c->q4_maximum_position-EPS&&cmd->q4_linear_velocity>0))cmd->q4_linear_velocity=0;sat->q1_dot=cmd->q1_rotary_velocity;e=manipulator_linear_velocity_to_joint_velocity(s->q2,cmd->q2_linear_velocity,&c->q2_actuator,&sat->q2_dot);if(e!=MANIP_OK)return e;e=manipulator_linear_velocity_to_joint_velocity(s->q3,cmd->q3_linear_velocity,&c->q3_actuator,&sat->q3_dot);if(e!=MANIP_OK)return e;sat->q4_dot=cmd->q4_linear_velocity;return MANIP_OK;}
ManipulatorStatus manipulator_velocity_control_step(const ManipulatorConfig *c,ManipulatorState *s,ManipulatorCartesianVelocity v,double dt,ManipulatorActuatorCommand *cmd,ManipulatorJointVelocity *ap){if(!c||!s||dt<=0)return MANIP_ERROR_INVALID_ARGUMENT;ManipulatorJointVelocity req,sat;ManipulatorActuatorCommand out;ManipulatorStatus e=manipulator_estimate_joint_velocity(c,s,v,&req);if(e!=MANIP_OK)return e;e=manipulator_joint_velocity_to_actuator_command(c,s,req,&out,&sat);if(e!=MANIP_OK)return e;double q1=s->q1+sat.q1_dot*dt,q2=s->q2+sat.q2_dot*dt,q3=s->q3+sat.q3_dot*dt,q4=clamp(s->q4+sat.q4_dot*dt,c->q4_minimum_position,c->q4_maximum_position);e=manipulator_update_state_from_joints(c,q1,q2,q3,q4,s);if(e!=MANIP_OK)return e;if(cmd)*cmd=out;if(ap)*ap=sat;return MANIP_OK;}
void manipulator_cartesian_velocity_from_joint_velocity(const ManipulatorState *s,ManipulatorJointVelocity q,ManipulatorCartesianVelocity *v){double x[4]={q.q1_dot,q.q2_dot,q.q3_dot,q.q4_dot},o[3]={0};for(int r=0;r<3;r++)for(int k=0;k<4;k++)o[r]+=s->Jv[r][k]*x[k];v->vx=o[0];v->vy=o[1];v->vz=o[2];}


/* ===================== CLI TEST PROGRAM ===================== */
#include <errno.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif
#define D2R(x) ((x)*M_PI/180.0)
#define R2D(x) ((x)*180.0/M_PI)
static int pd(const char *s,double *v){char *e;errno=0;*v=strtod(s,&e);return s!=e&&*e=='\0'&&errno!=ERANGE;}
static void usage(const char *p){printf("Usage:\n  %s fk q1_deg q2_deg q3_deg q4\n  %s jac q1_deg q2_deg q3_deg q4\n  %s ik x y z selected_q4\n  %s sim q1_deg q2_deg q3_deg q4 vx vy vz duration dt\n",p,p,p,p);}
static int init(const ManipulatorConfig*c,char **a,int k,ManipulatorState*s){double q1,q2,q3,q4;if(!pd(a[k],&q1)||!pd(a[k+1],&q2)||!pd(a[k+2],&q3)||!pd(a[k+3],&q4))return 0;ManipulatorStatus e=manipulator_update_state_from_joints(c,D2R(q1),D2R(q2),D2R(q3),q4,s);if(e!=MANIP_OK){fprintf(stderr,"init: %s\n",manipulator_status_string(e));return 0;}return 1;}
int main(int argc,char **argv){ManipulatorConfig c;ManipulatorState s;manipulator_default_config(&c);if(argc<2){usage(argv[0]);return 1;}if(!strcmp(argv[1],"fk")){if(argc!=6||!init(&c,argv,2,&s)){usage(argv[0]);return 1;}for(int r=0;r<4;r++){for(int k=0;k<4;k++)printf("%12.6f ",s.T04[r][k]);puts("");}printf("x=%.6f y=%.6f z=%.6f\nlq2=%.6f lq3=%.6f\n",s.x,s.y,s.z,s.q2_actuator_length,s.q3_actuator_length);return 0;}if(!strcmp(argv[1],"jac")){if(argc!=6||!init(&c,argv,2,&s)){usage(argv[0]);return 1;}for(int r=0;r<6;r++){for(int k=0;k<4;k++)printf("%12.6f ",s.J[r][k]);puts("");}return 0;}if(!strcmp(argv[1],"ik")){double x,y,z,q4;ManipulatorIKSolution sol[MANIP_MAX_IK_SOLUTIONS];size_t n=0;if(argc!=6||!pd(argv[2],&x)||!pd(argv[3],&y)||!pd(argv[4],&z)||!pd(argv[5],&q4)){usage(argv[0]);return 1;}ManipulatorStatus e=manipulator_inverse_position_for_q4(&c,x,y,z,q4,sol,&n);if(e!=MANIP_OK&&e!=MANIP_ERROR_SINGULAR){fprintf(stderr,"ik: %s\n",manipulator_status_string(e));return 1;}for(size_t i=0;i<n;i++)printf("%zu: q1=%.6f q2=%.6f q3=%.6f q4=%.6f\n",i+1,R2D(sol[i].q1),R2D(sol[i].q2),R2D(sol[i].q3),sol[i].q4);return 0;}if(!strcmp(argv[1],"sim")){double dur,dt;ManipulatorCartesianVelocity v,ach={0};ManipulatorActuatorCommand cmd={0};ManipulatorJointVelocity qd={0};if(argc!=11||!init(&c,argv,2,&s)||!pd(argv[6],&v.vx)||!pd(argv[7],&v.vy)||!pd(argv[8],&v.vz)||!pd(argv[9],&dur)||!pd(argv[10],&dt)||dt<=0){usage(argv[0]);return 1;}puts("time,x,y,z,q1_deg,q2_deg,q3_deg,q4,lq2,lq3,cmd_q1,cmd_lq2,cmd_lq3,cmd_q4,ach_vx,ach_vy,ach_vz");for(double t=0;t<=dur+dt/2;t+=dt){if(t>0){ManipulatorStatus e=manipulator_velocity_control_step(&c,&s,v,dt,&cmd,&qd);if(e!=MANIP_OK){fprintf(stderr,"sim stopped t=%.6f: %s\n",t,manipulator_status_string(e));return 1;}manipulator_cartesian_velocity_from_joint_velocity(&s,qd,&ach);}printf("%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f\n",t,s.x,s.y,s.z,R2D(s.q1),R2D(s.q2),R2D(s.q3),s.q4,s.q2_actuator_length,s.q3_actuator_length,cmd.q1_rotary_velocity,cmd.q2_linear_velocity,cmd.q3_linear_velocity,cmd.q4_linear_velocity,ach.vx,ach.vy,ach.vz);}return 0;}usage(argv[0]);return 1;}
